; Xdebug configuration for development

[xdebug]
xdebug.mode = develop,debug,coverage
xdebug.start_with_request = trigger
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.log = /tmp/xdebug.log
xdebug.idekey = PHPSTORM

; Coverage
xdebug.coverage_enable = 1