#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./scripts/bump-version.sh && \
cd backend && composer lint && \
composer rector && \
cd .. && actionlint .github/workflows/*.yml 2>/dev/null || true
